---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/people":
    get:
      summary: list people
      responses:
        '200':
          description: successful
    post:
      summary: create person
      responses:
        '200':
          description: successful
  "/api/v1/people/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show person
      responses:
        '200':
          description: successful
    patch:
      summary: update person
      responses:
        '200':
          description: successful
    put:
      summary: update person
      responses:
        '200':
          description: successful
    delete:
      summary: delete person
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost
