default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: irizaga00

development:
  <<: *default
  database: raffle_development

test:
  <<: *default
  database: raffle_test

production:
  <<: *default
  database: raffle_production
  username: postgres
  password: irizaga00
